# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='description',
            new_name='message',
        ),
    ]
